### ISSUE TITLE
Settings page opens upon entering/leaving instance

### ISSUE THREAD

**Issue by mortiaqt** [Odjur/WoWSplit#2]
After a loading screen, the settings page seems to open regardless of its status before the load screen

https://youtu.be/zlZc8aSDKRo

**Comment by mortiaqt** [comment]
additionally, the settings page opens when interacting with the controls (start/pause/split etc), unsure if that is related

**Comment by Odjur** [comment]
Fixed settings page staying open. Opening the settings menu with right-clicks on the UI is the intended method of opening it (not documented, I'll get on that one of these days :).
